on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Bogdanp/setup-racket@v1.9.1
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing hollow_knight_achievement_order_randomizer and its dependencies
        run: raco pkg install --no-docs --auto --name hollow_knight_achievement_order_randomizer
      - name: Compiling hollow_knight_achievement_order_randomizer and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps hollow_knight_achievement_order_randomizer
      - name: Testing hollow_knight_achievement_order_randomizer
        run: raco test -x -p hollow_knight_achievement_order_randomizer
